---
EXTENDS:
    - "https://raw.githubusercontent.com/llaville/.github/refs/heads/master/.mega-linter-base.yml"
ENABLE:
    - ACTION
    - EDITORCONFIG
    - MARKDOWN
    - PHP
    - YAML
DISABLE_LINTERS:
    - MARKDOWN_MARKDOWN_TABLE_FORMATTER
    - MARKDOWN_MARKDOWN_LINK_CHECK
    - PHP_PSALM
    - PHP_PHPCSFIXER
    - YAML_V8R
JSON_PRETTIER_FILTER_REGEX_EXCLUDE: "(composer.json)"
PHP_PHPSTAN_CONFIG_FILE: "phpstan.neon.dist"
PRINT_ALL_FILES: false
