variant = "loose"

[[issues]]
file = "src/Console/Application.php"
code = "no-isset"
message = "Use of the `isset` construct."
count = 1

[[issues]]
file = "src/Console/Command/ConvertCommand.php"
code = "cyclomatic-complexity"
message = "Class has high complexity."
count = 1

[[issues]]
file = "src/Console/Command/ConvertCommand.php"
code = "no-assign-in-condition"
message = "Avoid assignments in conditions."
count = 1

[[issues]]
file = "src/Console/Command/ConvertCommand.php"
code = "no-else-clause"
message = "Avoid `else` clauses."
count = 2

[[issues]]
file = "src/Console/Command/ConvertCommand.php"
code = "no-empty"
message = "Use of the `empty` construct."
count = 5

[[issues]]
file = "src/Converter/AbstractConverter.php"
code = "cyclomatic-complexity"
message = "Class has high complexity."
count = 1

[[issues]]
file = "src/Converter/AbstractConverter.php"
code = "kan-defect"
message = "Class has a high kan defect score."
count = 1

[[issues]]
file = "src/Converter/AbstractConverter.php"
code = "no-else-clause"
message = "Avoid `else` clauses."
count = 2

[[issues]]
file = "src/Converter/AbstractConverter.php"
code = "no-empty"
message = "Use of the `empty` construct."
count = 24

[[issues]]
file = "src/Converter/AbstractConverter.php"
code = "no-error-control-operator"
message = "Unsafe use of error control operator `@`."
count = 5

[[issues]]
file = "src/Converter/AbstractConverter.php"
code = "no-global"
message = "Unsafe use of `$GLOBALS` variable."
count = 1

[[issues]]
file = "src/Converter/AbstractConverter.php"
code = "prefer-early-continue"
message = "Consider using early continue pattern to reduce nesting."
count = 1

[[issues]]
file = "src/Converter/AbstractConverter.php"
code = "too-many-methods"
message = "Class has too many methods."
count = 1

[[issues]]
file = "src/Converter/AbstractConverter.php"
code = "too-many-properties"
message = "Class has too many properties."
count = 1

[[issues]]
file = "src/Converter/Normalizer/CheckstyleNormalizer.php"
code = "no-else-clause"
message = "Avoid `else` clauses."
count = 1

[[issues]]
file = "src/Converter/Normalizer/CheckstyleNormalizer.php"
code = "no-empty"
message = "Use of the `empty` construct."
count = 2

[[issues]]
file = "src/Converter/Normalizer/ComposerNormalizer.php"
code = "halstead"
message = "Method has a high halstead volume"
count = 1

[[issues]]
file = "src/Converter/Normalizer/ComposerNormalizer.php"
code = "kan-defect"
message = "Class has a high kan defect score."
count = 1

[[issues]]
file = "src/Converter/Normalizer/ComposerNormalizer.php"
code = "no-isset"
message = "Use of the `isset` construct."
count = 2

[[issues]]
file = "src/Converter/Normalizer/ComposerNormalizer.php"
code = "no-multi-assignments"
message = "Avoid multiple assignments in a single statement."
count = 1

[[issues]]
file = "src/Converter/Normalizer/ComposerNormalizer.php"
code = "prefer-early-continue"
message = "Consider using early continue pattern to reduce nesting."
count = 1

[[issues]]
file = "src/Converter/Normalizer/PhpCsNormalizer.php"
code = "kan-defect"
message = "Class has a high kan defect score."
count = 1

[[issues]]
file = "src/Converter/Normalizer/PhpCsNormalizer.php"
code = "no-isset"
message = "Use of the `isset` construct."
count = 2

[[issues]]
file = "src/Converter/Normalizer/PhpMdNormalizer.php"
code = "cyclomatic-complexity"
message = "Class has high complexity."
count = 1

[[issues]]
file = "src/Converter/Normalizer/PhpMdNormalizer.php"
code = "kan-defect"
message = "Class has a high kan defect score."
count = 1

[[issues]]
file = "src/Converter/Normalizer/PhpMdNormalizer.php"
code = "no-else-clause"
message = "Avoid `else` clauses."
count = 2

[[issues]]
file = "src/Converter/Normalizer/PhpMdNormalizer.php"
code = "no-empty"
message = "Use of the `empty` construct."
count = 4

[[issues]]
file = "src/Converter/Normalizer/SarifNormalizer.php"
code = "braced-string-interpolation"
message = "Unbraced variable in string interpolation."
count = 1

[[issues]]
file = "src/Converter/PhpCsConverter.php"
code = "no-global"
message = "Unsafe use of `$GLOBALS` variable."
count = 1

[[issues]]
file = "src/Converter/PhpCsConverter.php"
code = "prefer-early-continue"
message = "Consider using early continue pattern to reduce nesting."
count = 1

[[issues]]
file = "src/Converter/PhpLintConverter.php"
code = "no-global"
message = "Unsafe use of `$GLOBALS` variable."
count = 1

[[issues]]
file = "src/Converter/PhpLintConverter.php"
code = "prefer-early-continue"
message = "Consider using early continue pattern to reduce nesting."
count = 1

[[issues]]
file = "src/Converter/Reporter/PhpCsReport.php"
code = "excessive-parameter-list"
message = "Parameter list is too long."
count = 1

[[issues]]
file = "src/Converter/Reporter/TwigCsFixerReporter.php"
code = "no-boolean-flag-parameter"
message = "Avoid boolean flag parameters."
count = 1

[[issues]]
file = "src/Converter/Source/AbstractSource.php"
code = "kan-defect"
message = "Class has a high kan defect score."
count = 1

[[issues]]
file = "src/Converter/Source/AbstractSource.php"
code = "prefer-early-continue"
message = "Consider using early continue pattern to reduce nesting."
count = 1

[[issues]]
file = "src/Converter/Source/ComposerSource.php"
code = "no-empty"
message = "Use of the `empty` construct."
count = 1

[[issues]]
file = "src/Converter/Source/EcsSource.php"
code = "no-empty"
message = "Use of the `empty` construct."
count = 1

[[issues]]
file = "src/Converter/Source/EcsSource.php"
code = "no-isset"
message = "Use of the `isset` construct."
count = 1

[[issues]]
file = "src/Converter/Source/PhanSource.php"
code = "no-empty"
message = "Use of the `empty` construct."
count = 1

[[issues]]
file = "src/Converter/Source/PhpCsFixerSource.php"
code = "no-empty"
message = "Use of the `empty` construct."
count = 1

[[issues]]
file = "src/Converter/Source/PhpCsSource.php"
code = "no-empty"
message = "Use of the `empty` construct."
count = 1

[[issues]]
file = "src/Converter/Source/PhpCsSource.php"
code = "no-isset"
message = "Use of the `isset` construct."
count = 1

[[issues]]
file = "src/Converter/Source/PhpLintSource.php"
code = "no-empty"
message = "Use of the `empty` construct."
count = 1

[[issues]]
file = "src/Converter/Source/PhpMdSource.php"
code = "no-empty"
message = "Use of the `empty` construct."
count = 1

[[issues]]
file = "src/Converter/Source/PhpStanSource.php"
code = "no-empty"
message = "Use of the `empty` construct."
count = 1

[[issues]]
file = "src/Converter/Source/RectorSource.php"
code = "no-empty"
message = "Use of the `empty` construct."
count = 1

[[issues]]
file = "src/Converter/Source/TwigCsFixerSource.php"
code = "no-empty"
message = "Use of the `empty` construct."
count = 1

[[issues]]
file = "src/Factory/ConverterFactory.php"
code = "too-many-methods"
message = "Class has too many methods."
count = 1

[[issues]]
file = "src/Factory/SourceFactory.php"
code = "too-many-methods"
message = "Class has too many methods."
count = 1

[[issues]]
file = "tests/bootstrap.php"
code = "file-name"
message = "Class `Foo` should be in a file named `Foo.php`, found `bootstrap.php`."
count = 1

[[issues]]
file = "tests/bootstrap.php"
code = "strict-types"
message = "Missing `declare(strict_types=1);` statement at the beginning of the file."
count = 1
